### ISSUE TITLE
〇〇機能の不具合の修正

### ISSUE THREAD

**Issue by ghost** [otsubo-jyobi/Git-class#3]
# 概要

〇〇機能の〇〇でエラーが発生してる

# 再現手順

1. 〇〇を起動し、〇〇機能を実行する

# 修正しないとどう困るか

- 〇〇要件を実現することができない

# 原因

- データベースの操作でエラーが発生している

# 修正案

- [x]  〇〇機能のSQLを修正する

**Comment by otsubo-jyobi** [comment]
修正を確認できました。

**Comment by ghost** [comment]
修正を確認しました。
